#!/bin/bash
# AI-WORKFLOW-MANAGED: generated by setup-ai-workflow.sh; edit source templates or keep a backup before customizing.
# ralph-remote.sh — remote orchestration for a Ralph run (GitHub Actions).
#
# Triggered by .github/workflows/ralph-remote.yml on a push to a ralph/<slug>
# branch carrying an approved plan (prd/PRD.md). This wrapper owns the GitHub side
# only — tracking issue, branch push, pull request, status updates — and delegates
# ALL agent work and local git to ralph.sh:
#
#   1. open a tracking issue (label: ralph:run)
#   2. ./ralph.sh --decompose   (plan -> issues/, committed by Ralph)
#   3. post the issue checklist
#   4. ./ralph.sh               (dev/QA loop; archives the PRD on success)
#   5. push the branch and open a PR (success), or report the stop (failure).
#
# A retry whose branch already decomposed the CURRENT PRD skips 2-3 (and the
# panel/scope gate) and resumes the loop directly; a retry after the plan
# completed (PRD archived, no issues left) skips 2-4 and only ensures the PR
# exists. During 4, the progress hook pushes each closed issue so an ephemeral
# runner cannot lose finished work, and `--preserve-wip` (invoked by the
# workflow's always() step) commits + pushes in-flight work on cancellation.
#
# The runner is an ephemeral sandbox, so the claude developer agent runs with
# bypassPermissions (CLAUDECODE_SANDBOX=1, --unsafe-bypass). Set
# RALPH_REMOTE_DRYRUN=1 to echo every GitHub/push side effect instead of doing it.
set -uo pipefail

DRYRUN="${RALPH_REMOTE_DRYRUN:-0}"
BASE_BRANCH="${RALPH_BASE_BRANCH:-main}"
SERVER="${GITHUB_SERVER_URL:-https://github.com}"
REPO="${GITHUB_REPOSITORY:-}"

# The in-flight issue can damage .ralph.env along with the rest of the
# worktree, and --preserve-wip exists precisely to survive that damage: never
# EXECUTE the worktree copy on the preservation path — an injected `exit`,
# syntax error, or DRYRUN=1 would kill or defuse the very preservation it is
# meant to survive. Preservation reads the COMMITTED copy textually instead.
#
# Same override contract as ralph.sh: a one-off environment variable beats
# .ralph.env for every key this wrapper reads, so an operator can retry with
# e.g. PLAN_SCOPE_GATE=0 without editing committed config.
ENV_DEVELOPER_AGENT="${DEVELOPER_AGENT-}";   ENV_DEVELOPER_AGENT_SET=0;   [ "${DEVELOPER_AGENT+x}" = x ]   && ENV_DEVELOPER_AGENT_SET=1
ENV_QA_AGENT="${QA_AGENT-}";                 ENV_QA_AGENT_SET=0;          [ "${QA_AGENT+x}" = x ]          && ENV_QA_AGENT_SET=1
ENV_PANEL_AGENT="${PANEL_AGENT-}";           ENV_PANEL_AGENT_SET=0;       [ "${PANEL_AGENT+x}" = x ]       && ENV_PANEL_AGENT_SET=1
ENV_PANEL_ENABLED="${PANEL_ENABLED-}";       ENV_PANEL_ENABLED_SET=0;     [ "${PANEL_ENABLED+x}" = x ]     && ENV_PANEL_ENABLED_SET=1
ENV_PLAN_SCOPE_GATE="${PLAN_SCOPE_GATE-}";   ENV_PLAN_SCOPE_GATE_SET=0;   [ "${PLAN_SCOPE_GATE+x}" = x ]   && ENV_PLAN_SCOPE_GATE_SET=1
ENV_RALPH_PRD_DIR="${RALPH_PRD_DIR-}";       ENV_RALPH_PRD_DIR_SET=0;     [ "${RALPH_PRD_DIR+x}" = x ]     && ENV_RALPH_PRD_DIR_SET=1
ENV_RALPH_PRD_FILE="${RALPH_PRD_FILE-}";     ENV_RALPH_PRD_FILE_SET=0;    [ "${RALPH_PRD_FILE+x}" = x ]    && ENV_RALPH_PRD_FILE_SET=1
ENV_RALPH_ISSUES_DIR="${RALPH_ISSUES_DIR-}"; ENV_RALPH_ISSUES_DIR_SET=0;  [ "${RALPH_ISSUES_DIR+x}" = x ]  && ENV_RALPH_ISSUES_DIR_SET=1
ENV_CODEX_SANDBOX="${CODEX_SANDBOX-}";       ENV_CODEX_SANDBOX_SET=0;     [ "${CODEX_SANDBOX+x}" = x ]     && ENV_CODEX_SANDBOX_SET=1
if [ "${1:-}" != "--preserve-wip" ]; then
  # shellcheck disable=SC1091
  [ -f .ralph.env ] && . ./.ralph.env
  [ "$ENV_DEVELOPER_AGENT_SET" -eq 1 ]  && DEVELOPER_AGENT="$ENV_DEVELOPER_AGENT"
  [ "$ENV_QA_AGENT_SET" -eq 1 ]         && QA_AGENT="$ENV_QA_AGENT"
  [ "$ENV_PANEL_AGENT_SET" -eq 1 ]      && PANEL_AGENT="$ENV_PANEL_AGENT"
  [ "$ENV_PANEL_ENABLED_SET" -eq 1 ]    && PANEL_ENABLED="$ENV_PANEL_ENABLED"
  [ "$ENV_PLAN_SCOPE_GATE_SET" -eq 1 ]  && PLAN_SCOPE_GATE="$ENV_PLAN_SCOPE_GATE"
  [ "$ENV_RALPH_PRD_DIR_SET" -eq 1 ]    && RALPH_PRD_DIR="$ENV_RALPH_PRD_DIR"
  [ "$ENV_RALPH_PRD_FILE_SET" -eq 1 ]   && RALPH_PRD_FILE="$ENV_RALPH_PRD_FILE"
  [ "$ENV_RALPH_ISSUES_DIR_SET" -eq 1 ] && RALPH_ISSUES_DIR="$ENV_RALPH_ISSUES_DIR"
  [ "$ENV_CODEX_SANDBOX_SET" -eq 1 ]    && CODEX_SANDBOX="$ENV_CODEX_SANDBOX"
fi
RALPH_PRD_DIR="${RALPH_PRD_DIR:-prd}"
RALPH_PRD_FILE="${RALPH_PRD_FILE:-$RALPH_PRD_DIR/PRD.md}"
RALPH_ISSUES_DIR="${RALPH_ISSUES_DIR:-issues}"

log() { echo "ralph-remote: $*"; }
die() { echo "ralph-remote: $*" >&2; exit 1; }

comment_issue() {
  local num="$1" body="$2"
  if [ "$DRYRUN" = "1" ]; then
    echo "[dryrun] gh issue comment $num -- ${body%%$'\n'*}"
  else
    gh issue comment "$num" --body "$body" >/dev/null 2>&1 || true
  fi
}

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository."

branch="${GITHUB_REF_NAME:-$(git rev-parse --abbrev-ref HEAD)}"
case "$branch" in
  ralph/*) slug="${branch#ralph/}" ;;
  *) die "branch '$branch' is not a ralph/<slug> branch." ;;
esac

export CLAUDECODE_SANDBOX=1
git config user.name  >/dev/null 2>&1 || git config user.name  "ralph-bot"
git config user.email >/dev/null 2>&1 || git config user.email "ralph-bot@users.noreply.github.com"

# The run's FINAL push must carry [ralph skip] on HEAD, or it would re-trigger
# ralph-remote.yml and spawn a duplicate run once this one finishes (mid-run
# persistence pushes rely on the workflow's ralph-bot committer check instead —
# their commits are never rewritten). Only called when HEAD advanced past the
# triggering commit ($trigger_head), so the human's pushed commit is never
# rewritten and the push stays a fast-forward.
trigger_head=$(git rev-parse --verify HEAD)
mark_head_to_skip_remote_retrigger() {
  local msg_file remote_tip remote_out remote_known
  if git log -1 --pretty=%B | grep -q '\[ralph skip\]'; then
    return 0
  fi
  if [ -n "$(git status --porcelain)" ]; then
    # Amending with a dirty tree would sweep staged changes into the commit.
    # The index is not pushed anyway: drop it and add an empty marker commit.
    git reset -q
    git -c core.hooksPath=/dev/null commit --allow-empty -m "chore: mark remote push [ralph skip]" >/dev/null
    return $?
  fi
  # A persistence push may already have published HEAD; amending a published
  # commit would make the final push a rejected non-fast-forward. Mark those
  # with an empty commit on top instead — and treat a FAILED lookup (transient
  # network error) the same: guessing "unpublished" would rewrite a possibly
  # published commit, while the empty marker stays fast-forward either way.
  remote_tip=""; remote_known=0
  if remote_out=$(git ls-remote --quiet origin "refs/heads/${branch:-}" 2>/dev/null); then
    remote_known=1
    remote_tip=$(printf '%s' "$remote_out" | cut -f1)
  fi
  if [ "$remote_known" -eq 0 ] || [ "$remote_tip" = "$(git rev-parse --verify HEAD)" ]; then
    git -c core.hooksPath=/dev/null commit --allow-empty -m "chore: mark remote push [ralph skip]" >/dev/null
    return $?
  fi
  msg_file=$(mktemp "${TMPDIR:-/tmp}/ralph-commit-msg.XXXXXX") || return 1
  git log -1 --pretty=%B > "$msg_file"
  printf '\n[ralph skip]\n' >> "$msg_file"
  git -c core.hooksPath=/dev/null commit --amend -F "$msg_file" >/dev/null
  rm -f "$msg_file"
}

# A failed loop leaves the last attempt's work UNCOMMITTED. Discarding it would
# waste both the work and any QA findings, so preserve it as a wip(<slug>)
# commit: a retry run resumes the issue from it (ralph.sh find_wip_base reads
# the Issue-Base trailer), and [ralph skip] keeps the push from re-triggering
# the workflow. Identity comes from .git/ralph.qa-exhausted (QA exhaustion,
# findings ride in the body) or .git/ralph.current-issue (any other mid-issue
# failure). With NEITHER, nothing is committed: find_wip_base only matches
# wip(<slug>), so a wip(unknown) commit could never be resumed and its edits
# would ride into the next run's QA baseline unreviewed.
#
# Issue specs are Ralph-owned control files, never preservable work: a mutated
# or deleted spec committed into the snapshot would rewrite the retry's issue
# queue (deleted specs vanish from pick_issue) and gate later work against a
# forged baseline, so $RALPH_ISSUES_DIR is always excluded — the retry's fresh
# checkout restores the committed specs. The same goes for the machinery the
# retry EXECUTES before any agent could fix it — .ralph.env (sourced),
# ralph.sh / ralph-remote.sh (run), .github/workflows (run by Actions, and a
# push touching them can be rejected outright for tokens without workflow
# scope): committing a damaged copy would brick every retry.
commit_wip_after_failed_loop() {
  local exhausted current history slug rounds findings subject parent msg_file issues_dir
  issues_dir="${RALPH_ISSUES_DIR:-issues}"
  exhausted=$(git rev-parse --git-path ralph.qa-exhausted 2>/dev/null)
  current=$(git rev-parse --git-path ralph.current-issue 2>/dev/null)
  set -- ":(exclude)${issues_dir}" ":(exclude).ralph.env" ":(exclude)ralph.sh" \
         ":(exclude)ralph-remote.sh" ":(exclude).github/workflows"

  if [ -n "$(git status --porcelain -- . "$@")" ]; then
    slug=""; rounds=""; findings=""
    if [ -s "$exhausted" ]; then
      slug=$(sed -n 's/^issue=//p' "$exhausted" | head -n 1)
      rounds=$(sed -n 's/^rounds=//p' "$exhausted" | head -n 1)
      findings=$(sed -n '/^$/,$p' "$exhausted" | head -c 20000)
    fi
    if [ -n "$slug" ]; then
      subject="QA round ${rounds:-?} attempt"
    elif [ -s "$current" ]; then
      slug=$(head -n 1 "$current")
      subject="interrupted attempt"
      # A mid-cycle interruption can hold FAIL findings that never reached
      # exhaustion (ralph.qa-findings-history). Carry them in the body so the
      # retry's seeded QA can still verify they were addressed.
      history=$(git rev-parse --git-path ralph.qa-findings-history 2>/dev/null)
      [ -s "$history" ] && findings=$(head -c 20000 "$history")
    fi
    if [ -z "$slug" ]; then
      log "uncommitted changes but no recorded issue identity; NOT preserving them as WIP (an unresumable wip(unknown) commit would poison the retry's QA baseline)."
      return 0
    fi
    parent=$(git rev-parse --verify HEAD 2>/dev/null) || return 1
    msg_file=$(mktemp "${TMPDIR:-/tmp}/ralph-wip-msg.XXXXXX") || return 1
    {
      printf 'wip(%s): %s [ralph skip]\n\n' "$slug" "$subject"
      [ -n "$findings" ] && printf '%s\n\n' "$findings"
      printf 'Issue-Base: %s\n' "$parent"
    } > "$msg_file"
    # Reset first: an interrupted close leaves the spec's deletion STAGED, and
    # a pathspec exclude on `git add` would not unstage it.
    if ! git reset -q || ! git add -A -- . "$@" \
       || ! git -c core.hooksPath=/dev/null commit -F "$msg_file" >/dev/null; then
      rm -f "$msg_file"
      return 1
    fi
    rm -f "$msg_file"
    log "preserved the failed issue's work-in-progress as a wip($slug) commit."
    return 0
  fi

  [ -n "$(git status --porcelain)" ] \
    && log "the only uncommitted changes touch Ralph-owned control files (issue specs, config, or the run scripts); NOT preserving them — the retry's checkout restores the committed versions."

  # No preservable work in the tree — but one COMMITTED state still needs
  # marking: the gap inside commit_completed_issue where "implement <slug>"
  # landed and "close <slug>" did not. find_wip_base cannot see plain
  # implement commits, so an unmarked retry's developer would find nothing to
  # do and the issue would sit open until the no-progress stop. An empty
  # wip(<slug>) marker (Issue-Base = the implement commit's parent) makes the
  # retry resume: QA re-judges the committed diff and the close finally lands.
  slug=""
  [ -s "$current" ] && slug=$(head -n 1 "$current")
  [ -n "$slug" ] || return 0
  [ "$(git log -1 --pretty=%s 2>/dev/null)" = "implement $slug" ] || return 0
  parent=$(git rev-parse --verify HEAD^ 2>/dev/null) || return 0
  msg_file=$(mktemp "${TMPDIR:-/tmp}/ralph-wip-msg.XXXXXX") || return 1
  {
    printf 'wip(%s): committed implementation awaiting closure [ralph skip]\n\n' "$slug"
    printf 'Issue-Base: %s\n' "$parent"
  } > "$msg_file"
  if ! git reset -q || ! git -c core.hooksPath=/dev/null commit --allow-empty -F "$msg_file" >/dev/null; then
    rm -f "$msg_file"
    return 1
  fi
  rm -f "$msg_file"
  log "marked the committed-but-unclosed implementation of $slug as a resumable wip($slug) commit."
}

# --- --preserve-wip: the workflow's cancellation safety net -----------------
# A cancelled or timed-out job kills this script mid-loop, so the normal
# failure path (WIP preservation + push) never runs. The workflow re-invokes
# this mode from an always() step during the cancellation grace period — via a
# trusted copy captured before any agent ran, since the in-flight issue may
# have damaged the worktree's copy: commit any dirty work under the recorded
# issue identity and push whatever is unpushed, marked so the push cannot
# re-trigger a run. No tracking-issue traffic and no agent calls happen here,
# so it needs no agent credentials.
if [ "${1:-}" = "--preserve-wip" ]; then
  # Layout comes from the last COMMITTED .ralph.env (agents cannot commit, so
  # HEAD's copy is trusted) — the worktree copy was deliberately not sourced
  # above. Extracted textually, and only accepted as a plain path token; a
  # mangled value falls back to the default rather than executing anything.
  layout_v=$( (git show "HEAD:.ralph.env" 2>/dev/null || true) \
    | sed -n 's/^RALPH_ISSUES_DIR=//p' | head -n 1)
  case "$layout_v" in
    ''|*[!A-Za-z0-9._/-]*) : ;;
    *) RALPH_ISSUES_DIR="$layout_v" ;;
  esac
  # A failed WIP commit must fail the step: exiting 0 here would let the runner
  # tear down and silently discard the very changes this mode exists to save.
  # Still push any commits that DO exist first — salvage what we can.
  wip_err=0
  commit_wip_after_failed_loop || wip_err=1
  remote_tip=$( (git ls-remote --quiet origin "refs/heads/$branch" 2>/dev/null || true) | cut -f1)
  head_now=$(git rev-parse --verify HEAD)
  if [ -n "$remote_tip" ] && [ "$remote_tip" = "$head_now" ]; then
    [ "$wip_err" -eq 0 ] || die "could not commit the dirty work-in-progress; it is NOT on origin and will be lost with the runner."
    log "nothing unpushed; origin already holds $head_now."
    exit 0
  fi
  if [ "$DRYRUN" = "1" ]; then
    echo "[dryrun] git push origin HEAD:$branch"
  else
    mark_head_to_skip_remote_retrigger || true
    git push origin "HEAD:$branch" || die "could not push the preserved work."
    log "pushed the preserved work to $branch."
  fi
  [ "$wip_err" -eq 0 ] || die "pushed the existing commits, but the dirty work-in-progress could not be committed and will be lost with the runner."
  exit 0
fi

# --- plan-state detection ----------------------------------------------------
# Decides which stages a retry still needs BEFORE the credential preflight, so
# stages a resume skips cannot fail the run over credentials they never use.
#
# PLAN_COMPLETED: the loop finished and its persistence push landed (PRD
# archived, no issue files left), but the run died before the PR existed. Only
# the GitHub side (tracking issue + PR) remains — no agents run at all.
# already_decomposed: the branch already carries a decompose commit for the
# CURRENT PRD (same detection as ralph.sh restore_plan_state_from_history), so
# panel/scope gate/decompose are skipped and the loop resumes directly; the
# worst case otherwise is recreating and reimplementing every issue, including
# a full re-decompose after the last issue closed but the final audit failed.
PLAN_COMPLETED=0
already_decomposed=0
if [ -f "$RALPH_PRD_FILE" ]; then
  # Only decompose commits from the CURRENT plan lifecycle count: an archive
  # commit ends a plan, so anything at or before the latest one belongs to an
  # earlier plan. Without this bound, re-adding an archived PRD's identical
  # text on a reused branch would match the OLD decompose commit (the
  # endpoint-only diff is quiet), skip decomposition, and let the old plan's
  # close commits pass the new plan off as already implemented.
  latest_archive=$(git rev-list -n 1 --grep='^archive completed PRD' HEAD 2>/dev/null || true)
  if [ -n "$latest_archive" ]; then
    decompose_commit=$(git rev-list -n 1 --grep='^decompose PRD into issues' "${latest_archive}..HEAD" 2>/dev/null || true)
  else
    decompose_commit=$(git rev-list -n 1 --grep='^decompose PRD into issues' HEAD 2>/dev/null || true)
  fi
  if [ -n "$decompose_commit" ] && git diff --quiet "$decompose_commit" HEAD -- "$RALPH_PRD_FILE" 2>/dev/null; then
    already_decomposed=1
  fi
else
  # No active PRD. Distinguish three states before giving up:
  # (a) the branch is already merged — merge commits keep HEAD an ancestor of
  #     the base branch; squash/rebase merges rewrite IDs, so also ask GitHub
  #     for a merged PR. Either way: clean no-op, not a fresh completion.
  if git merge-base --is-ancestor HEAD "origin/$BASE_BRANCH" 2>/dev/null; then
    log "HEAD is already contained in $BASE_BRANCH (plan merged or branch empty); nothing to run. Push a new $RALPH_PRD_FILE to start another run."
    exit 0
  fi
  #     A reused ralph/<slug> branch keeps its historical merged PRs, and any
  #     of them would match by branch name alone — skipping a NEW plan that
  #     archived but died before its PR opened. Only a merged PR whose head is
  #     the CURRENT tip proves this plan merged.
  head_now=$(git rev-parse --verify HEAD 2>/dev/null || true)
  merged_pr=$( (gh pr list --head "$branch" --state merged --json number,headRefOid \
      --jq '.[] | "\(.number) \(.headRefOid)"' 2>/dev/null || true) \
    | awk -v oid="$head_now" '$2 == oid { print $1; exit }')
  if [ -n "$merged_pr" ]; then
    log "this branch's plan is already merged (PR #$merged_pr); nothing to run. Push a new $RALPH_PRD_FILE to start another run."
    exit 0
  fi
  # (b) the plan completed ON THIS BRANCH but the run died before the PR. Only
  #     branch-local archive commits count: one inherited from the base branch
  #     (an earlier, merged plan) must not make an unrelated ralph/* branch
  #     look completed.
  if git rev-parse --verify --quiet "origin/$BASE_BRANCH^{commit}" >/dev/null 2>&1; then
    archive_commit=$(git rev-list -n 1 --grep='^archive completed PRD' "origin/$BASE_BRANCH..HEAD" 2>/dev/null || true)
  else
    archive_commit=$(git rev-list -n 1 --grep='^archive completed PRD' HEAD 2>/dev/null || true)
  fi
  if [ -n "$archive_commit" ] && ! ls "$RALPH_ISSUES_DIR"/*.md >/dev/null 2>&1; then
    PLAN_COMPLETED=1
  else
    # (c) a genuine missing-PRD error.
    die "$RALPH_PRD_FILE not found on this branch; nothing to run."
  fi
fi

# The panel/scope-gate stages only run before decomposition; a resume skips
# them, so the panel-only agent must not be required (or preflighted) then.
PANEL_STAGES_PENDING=0
if [ "$PLAN_COMPLETED" -eq 0 ] && [ "$already_decomposed" -eq 0 ] \
   && { [ "${PANEL_ENABLED:-0}" = "1" ] || [ "${PLAN_SCOPE_GATE:-1}" = "1" ]; }; then
  PANEL_STAGES_PENDING=1
fi

# The developer agent runs in decompose and issue work (including QA-fix
# rounds). An audit-only resume — plan decomposed, every issue closed, only
# the final whole-plan audit pending — invokes the QA agent alone, so a dead
# developer credential must not block it.
DEV_STAGES_PENDING=1
if [ "$PLAN_COMPLETED" -eq 1 ] \
   || { [ "$already_decomposed" -eq 1 ] && ! ls "$RALPH_ISSUES_DIR"/*.md >/dev/null 2>&1; }; then
  DEV_STAGES_PENDING=0
fi

# --- 0. agent credentials preflight ----------------------------------------
# The workflow exports every RALPH_* secret to this step; unset secrets arrive
# as EMPTY variables, and an empty ANTHROPIC_API_KEY breaks the Claude CLI.
# Normalize here, before any agent runs, so failures are immediate and named.
[ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] || unset CLAUDE_CODE_OAUTH_TOKEN
[ -n "${ANTHROPIC_API_KEY:-}" ]      || unset ANTHROPIC_API_KEY
[ -n "${OPENAI_API_KEY:-}" ]         || unset OPENAI_API_KEY
if [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  # With both set the CLI would bill the metered key; the subscription wins.
  log "both Claude credentials present; using CLAUDE_CODE_OAUTH_TOKEN (subscription) and dropping ANTHROPIC_API_KEY."
  unset ANTHROPIC_API_KEY
fi

# Codex authenticates with the ChatGPT-subscription auth.json (from `codex login`),
# not an API key — the API-key path bills the metered account and dies with
# "Quota exceeded" when it holds no credits. Seed $CODEX_HOME/auth.json from the
# secret; the Codex CLI refreshes the token itself from there.
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
if [ -n "${RALPH_CODEX_AUTH_JSON:-}" ]; then
  mkdir -p "$CODEX_HOME"
  (umask 077 && printf '%s' "$RALPH_CODEX_AUTH_JSON" > "$CODEX_HOME/auth.json")
  log "seeded $CODEX_HOME/auth.json from RALPH_CODEX_AUTH_JSON."
fi
unset RALPH_CODEX_AUTH_JSON   # agents never need the raw secret in their env

# An agent's credentials are required only while a stage that invokes it is
# still pending (DEV_STAGES_PENDING / PANEL_STAGES_PENDING, computed above) —
# a resume that skips a stage must not be blocked by that stage's credential.
# The QA agent is always required: every non-completed state reaches QA.
uses_agent() {
  { [ "${DEV_STAGES_PENDING:-1}" -eq 1 ] && [ "${DEVELOPER_AGENT:-claude}" = "$1" ]; } \
    || [ "${QA_AGENT:-gemini}" = "$1" ] \
    || { [ "${PANEL_STAGES_PENDING:-1}" -eq 1 ] \
         && [ "${PANEL_AGENT:-${QA_AGENT:-gemini}}" = "$1" ]; }
}
# A completed-plan retry runs no agents at all: only the PR remains to be
# opened, and requiring agent credentials there would strand the branch.
if [ "${PLAN_COMPLETED:-0}" -eq 0 ]; then
  if uses_agent claude && [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -z "${ANTHROPIC_API_KEY:-}" ]; then
    die "no Claude credentials. Set the RALPH_CLAUDE_CODE_OAUTH_TOKEN secret (run 'claude setup-token' — Claude Pro/Max subscription) or RALPH_ANTHROPIC_API_KEY (metered API key, needs a funded balance)."
  fi
  if uses_agent codex && [ ! -f "$CODEX_HOME/auth.json" ] && [ -z "${OPENAI_API_KEY:-}" ]; then
    die "no Codex credentials. Run 'codex login' locally (headless machine: 'codex login --device-auth'), then: gh secret set RALPH_CODEX_AUTH_JSON < ~/.codex/auth.json"
  fi

  # Codex's own sandbox layer is broken on GitHub-hosted runners ("bwrap:
  # loopback: Failed RTM_NEWADDR" on every command it tries to run), and codex
  # does not fail the run over it — agents silently degrade, e.g. a QA reviewer
  # judging from the diff text alone because none of its commands execute. The
  # runner VM is already an ephemeral, single-purpose sandbox, so no-sandbox is
  # the correct mode here: force it, loudly. RALPH_KEEP_CODEX_SANDBOX=1 opts
  # out (for self-hosted runners where codex's sandbox actually works).
  if uses_agent codex && [ "${CODEX_SANDBOX:-danger-full-access}" != "danger-full-access" ] \
     && [ "${RALPH_KEEP_CODEX_SANDBOX:-0}" != "1" ]; then
    log "=================================================================="
    log "preflight: CODEX_SANDBOX=${CODEX_SANDBOX} does not work on GitHub-hosted"
    log "runners: codex's sandbox layer fails there and codex agents silently"
    log "degrade to judging from prompt text alone. Forcing"
    log "CODEX_SANDBOX=danger-full-access for this run. Set"
    log "RALPH_KEEP_CODEX_SANDBOX=1 (self-hosted runner) to keep your value."
    log "=================================================================="
    export CODEX_SANDBOX=danger-full-access
  fi

  # Cheap auth ping so a dead credential (expired token, empty API balance) fails
  # here with a named cause instead of deep in the loop. RALPH_PREFLIGHT_PING=0 skips.
  if uses_agent claude && [ "$DRYRUN" != "1" ] && [ "${RALPH_PREFLIGHT_PING:-1}" = "1" ]; then
    log "preflight: pinging the Claude API with the configured credential"
    ping_cmd=(claude -p 'Reply with exactly: ok' --model haiku)
    command -v timeout >/dev/null 2>&1 && ping_cmd=(timeout 180 "${ping_cmd[@]}")
    if ! ping_out=$("${ping_cmd[@]}" 2>&1); then
      printf '%s\n' "$ping_out" | tail -n 5 >&2
      die "Claude credential preflight failed (output above). If it mentions credit balance, switch to a subscription token: 'claude setup-token', then gh secret set RALPH_CLAUDE_CODE_OAUTH_TOKEN."
    fi
  fi
fi

branch_url="$SERVER/$REPO/tree/$branch"

# --- 1. tracking issue ----------------------------------------------------
issue_body="Autonomous Ralph run for branch \`$branch\`.

Plan: \`$RALPH_PRD_FILE\` ($branch_url)

This issue tracks progress. Ralph decomposes the plan into issues, works them one
at a time through the dev/QA gate, archives the PRD, and opens a PR for review.
Cancel the workflow run to stop."

if [ "$DRYRUN" = "1" ]; then
  issue_num=0
  log "[dryrun] would open tracking issue 'Ralph run: $slug'"
else
  gh label create ralph:run --color FBCA04 --description "Ralph autonomous run" --force >/dev/null 2>&1 || true
  # Retry of a stopped run: keep the slug's whole story in ONE issue. Reuse an
  # open tracking issue if present; otherwise reopen the one a failed run
  # closed (reason: not planned). Issues closed as COMPLETED by a merged PR are
  # never resurrected — a reused slug after a merge gets a fresh issue.
  issue_num=$(gh issue list --state open --label ralph:run --limit 200 \
    --json number,title --jq ".[] | select(.title==\"Ralph run: $slug\") | .number" | head -n 1)
  if [ -n "${issue_num:-}" ]; then
    log "reusing open tracking issue #$issue_num"
  else
    issue_num=$(gh issue list --state closed --label ralph:run --limit 200 \
      --json number,title,stateReason --jq ".[] | select(.title==\"Ralph run: $slug\") | select(.stateReason==\"NOT_PLANNED\") | .number" | head -n 1)
    if [ -n "${issue_num:-}" ]; then
      gh issue reopen "$issue_num" >/dev/null 2>&1 || true
      log "reopened tracking issue #$issue_num (retry of a failed run)"
    fi
  fi
  if [ -n "${issue_num:-}" ]; then
    comment_issue "$issue_num" "New run started for \`$branch\` (retry of a stopped run)."
  else
    if ! issue_url=$(gh issue create --title "Ralph run: $slug" --label ralph:run --body "$issue_body"); then
      die "failed to open tracking issue."
    fi
    issue_num=$(printf '%s' "$issue_url" | sed -E 's#.*/##')
    case "$issue_num" in
      ''|*[!0-9]*) die "could not parse tracking issue number from: $issue_url" ;;
    esac
    log "opened tracking issue #$issue_num: $issue_url"
  fi
fi

# --- progress hook (ralph.sh invokes this on decompose / close / complete) ---
# Config is passed by environment so the hook body needs no escaping. The
# repo's own hook (RALPH_PROGRESS_HOOK from .ralph.env) is captured first and
# chained after the issue comment, so custom notifications still fire remotely.
export RALPH_USER_PROGRESS_HOOK="${RALPH_PROGRESS_HOOK:-}"
export RALPH_ISSUE_NUM="$issue_num"
export RALPH_DRYRUN="$DRYRUN"
export RALPH_REMOTE_BRANCH="$branch"
hook_path="$(git rev-parse --git-path ralph-progress-hook.sh)"
cat > "$hook_path" <<'HOOK'
#!/bin/bash
set -uo pipefail
event="${1:-}"; slug="${2:-}"
case "$event" in
  run-start)     msg="Ralph run started." ;;
  panel-start)   msg="Plan-critique panel started." ;;
  panel-complete) msg="Plan-critique panel finished." ;;
  decomposed)    msg="Decomposed the plan into issues; starting the dev/QA loop." ;;
  issue-started) msg="Working on issue: $slug" ;;
  issue-closed)  msg="Closed issue: $slug" ;;
  issue-failed)  msg="Issue did not pass QA: $slug" ;;
  plan-complete) msg="All issues passed QA and the PRD was archived; opening a PR." ;;
  run-stopped)   msg="Ralph run stopped: $slug" ;;
  *)             msg="$event $slug" ;;
esac
if [ "${RALPH_DRYRUN:-0}" = "1" ]; then
  echo "[dryrun] gh issue comment ${RALPH_ISSUE_NUM:-0} -- $msg"
else
  gh issue comment "${RALPH_ISSUE_NUM:-0}" --body "$msg" >/dev/null 2>&1 || true
fi
# Persist finished work the moment it exists: the runner is ephemeral and the
# wrapper's post-loop push never happens on a cancelled/timed-out/lost run, so
# each closed issue (and the decompose/archive commits) is pushed immediately.
# These commits carry the ralph-bot committer, so the workflow's job condition
# skips the runs those pushes would otherwise re-trigger.
case "$event" in
  decomposed|issue-closed|plan-complete)
    if [ "${RALPH_DRYRUN:-0}" = "1" ]; then
      echo "[dryrun] git push origin HEAD:${RALPH_REMOTE_BRANCH:-}"
    elif [ -n "${RALPH_REMOTE_BRANCH:-}" ]; then
      git push origin "HEAD:refs/heads/${RALPH_REMOTE_BRANCH}" >/dev/null 2>&1 \
        || echo "ralph-progress-hook: push to origin failed; finished work stays only on this runner until the final push." >&2
    fi
    ;;
esac
# Chain the repo's own progress hook (RALPH_PROGRESS_HOOK from .ralph.env), so
# custom notifications (Slack, ntfy, ...) still fire on remote runs.
if [ -n "${RALPH_USER_PROGRESS_HOOK:-}" ] && [ -x "$RALPH_USER_PROGRESS_HOOK" ]; then
  "$RALPH_USER_PROGRESS_HOOK" "$@" || true
fi
HOOK
chmod +x "$hook_path"
export RALPH_PROGRESS_HOOK="$hook_path"

# --unsafe-bypass (bypassPermissions) is claude-only and safe here because the
# runner is an ephemeral sandbox. glm runs the same claude CLI via claude-glm, so
# it takes the same flag. codex brings its own sandbox; gemini uses its default
# permissions.
dev_extra=()
case "${DEVELOPER_AGENT:-claude}" in
  claude|glm) dev_extra=(--unsafe-bypass) ;;
esac
decompose_cmd=(./ralph.sh --decompose)
loop_cmd=(./ralph.sh)
panel_cmd=(./ralph.sh --review-plan)
if [ "${#dev_extra[@]}" -gt 0 ]; then
  decompose_cmd+=("${dev_extra[@]}")
  loop_cmd+=("${dev_extra[@]}")
fi

# --- 1b. plan-critique panel (opt-in, before decompose) -------------------
# Reviews prd/PRD.md with a multi-lens panel and commits prd/plan-review.md (it ships
# with the branch). Advisory by default; PANEL_BLOCKING=1 stops before decompose on a
# NEEDS CHANGES verdict. Needs PANEL_AGENT to be an agent provisioned on the runner.
if [ "$PANEL_STAGES_PENDING" -eq 1 ] && [ "${PANEL_ENABLED:-0}" = "1" ]; then
  log "running the plan-critique panel"
  "${panel_cmd[@]}"; panel_rc=$?
  case "$panel_rc" in
    0) comment_issue "$issue_num" "Plan-critique panel: READY TO HAND OFF ($RALPH_PRD_DIR/plan-review.md on the branch)." ;;
    3)
      comment_issue "$issue_num" "Plan-critique panel: NEEDS CHANGES ($RALPH_PRD_DIR/plan-review.md on the branch)."
      if [ "${PANEL_BLOCKING:-0}" = "1" ]; then
        if [ "$(git rev-parse --verify HEAD)" != "$trigger_head" ]; then
          mark_head_to_skip_remote_retrigger || true
        fi
        git push origin "HEAD:$branch" >/dev/null 2>&1 || true
        die "plan-critique panel returned NEEDS CHANGES (PANEL_BLOCKING=1); stopping before decompose."
      fi
      ;;
    *) comment_issue "$issue_num" "Plan-critique panel could not run (see logs); continuing to decompose." ;;
  esac
fi

# --- 2 + 3. decompose and post the checklist (skipped on resume) -----------
if [ "$PLAN_COMPLETED" -eq 1 ]; then
  log "plan already completed on this branch (PRD archived, all issues closed); ensuring the PR exists."
  comment_issue "$issue_num" "Resuming after completion: this plan is already implemented and archived on the branch; opening the PR."
elif [ "$already_decomposed" -eq 1 ]; then
  remaining=$(find "$RALPH_ISSUES_DIR" -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  log "plan already decomposed on this branch ($remaining issue file(s) remaining); skipping panel/scope gate/decompose."
  comment_issue "$issue_num" "Resuming: this plan is already decomposed on the branch ($remaining issue file(s) remaining). Skipping panel/scope gate/decompose and going straight to the dev/QA loop."
else
  log "decomposing plan into issues"
  "${decompose_cmd[@]}"; decompose_rc=$?
  if [ "$decompose_rc" -eq 3 ]; then
    scope_note=""
    [ -f "$RALPH_PRD_DIR/plan-scope.md" ] && scope_note=$(cat "$RALPH_PRD_DIR/plan-scope.md")
    comment_issue "$issue_num" "Plan rejected as over-scoped before decomposition (PLAN_SCOPE_GATE). Reduce \`$RALPH_PRD_FILE\` to one shippable slice and re-push; defer the rest to a later plan, keeping deferred slices behind a feature flag. No PR opened.

$scope_note"
    die "plan scope gate rejected the plan as too large; stopping before decomposition."
  elif [ "$decompose_rc" -ne 0 ]; then
    comment_issue "$issue_num" "Decomposition failed; see the workflow logs. No PR opened."
    die "decomposition failed."
  fi

  checklist=""
  for f in "$RALPH_ISSUES_DIR"/*.md; do
    if [ -e "$f" ]; then checklist="$checklist- [ ] $(basename "$f")
"; fi
  done
  comment_issue "$issue_num" "Planned issues:

$checklist"
fi

# --- 4. run the dev/QA loop (nothing left to run after completion) --------
if [ "$PLAN_COMPLETED" -eq 1 ]; then
  loop_rc=0
else
  log "running the dev/QA loop"
  "${loop_cmd[@]}"
  loop_rc=$?
fi

# --- 5. push + PR (success) or report the stop (failure) -----------------
wip_preserve_err=0
if [ "$DRYRUN" = "1" ]; then
  echo "[dryrun] git push origin HEAD:$branch"
else
  # A failed loop's uncommitted QA-fix work is preserved as a wip() commit
  # BEFORE the skip-marking below (whose dirty-tree fallback would discard it).
  # A preservation failure must not abort the push/report (salvage what
  # exists), but it must be LOUD: the run is already failing, and losing the
  # attempt silently would read as "nothing to preserve".
  if [ "$loop_rc" -ne 0 ] && ! commit_wip_after_failed_loop; then
    wip_preserve_err=1
    log "ERROR: the failed issue's uncommitted work could not be preserved as a wip() commit and will be lost with this runner."
  fi
  if [ "$(git rev-parse --verify HEAD)" != "$trigger_head" ]; then
    mark_head_to_skip_remote_retrigger || die "failed to mark commit to skip remote retrigger."
  else
    log "no new commits; leaving HEAD unamended before push."
  fi
  if ! git push origin "HEAD:$branch"; then
    comment_issue "$issue_num" "Git push failed; no PR opened. The workflow logs contain the failed push details, and work from this ephemeral runner may not be preserved."
    die "git push failed."
  fi
fi

if [ "$loop_rc" -eq 0 ] && ! ls "$RALPH_ISSUES_DIR"/*.md >/dev/null 2>&1 && [ ! -f "$RALPH_PRD_FILE" ]; then
  pr_body="Automated implementation of the plan on \`$branch\`.

Closes #$issue_num"
  # The plan's carried QA notes (deferred criteria, accepted assumptions) are
  # archived under the same stamp as the PRD; quote them in the PR body so the
  # human reviewer they are addressed to actually sees them.
  latest_prd_archive=$(ls -1 "$RALPH_PRD_DIR/archive/"*"-$(basename "$RALPH_PRD_FILE")" 2>/dev/null | sort | tail -n 1)
  if [ -n "$latest_prd_archive" ]; then
    stamp=$(basename "$latest_prd_archive"); stamp="${stamp%%-*}"
    qa_notes_archive="$RALPH_PRD_DIR/archive/$stamp-qa-notes.md"
    if [ -s "$qa_notes_archive" ]; then
      pr_body="$pr_body

## QA notes for the reviewer

Carried from the per-issue QA gates (committed at \`$qa_notes_archive\`):

\`\`\`
$(head -c 20000 "$qa_notes_archive")
\`\`\`"
    fi
  fi
  if [ "$DRYRUN" = "1" ]; then
    log "[dryrun] would open PR $branch -> $BASE_BRANCH (Closes #$issue_num)"
  else
    pr_url=$(gh pr create --base "$BASE_BRANCH" --head "$branch" --title "Ralph: $slug" --body "$pr_body" 2>/dev/null) \
      || pr_url=$(gh pr view "$branch" --json url -q .url 2>/dev/null) \
      || pr_url=""
    comment_issue "$issue_num" "Opened a PR for review: ${pr_url:-see the Pull Requests tab}"
    log "PR: ${pr_url:-<unknown>}"
  fi
  log "run complete."
else
  fail_body="Ralph stopped before completion (loop exit $loop_rc). The branch holds partial work; no PR opened."
  if [ "$wip_preserve_err" -eq 1 ]; then
    fail_body="$fail_body WARNING: the failed issue's uncommitted work could NOT be preserved as a wip() commit and was lost with the runner - check the workflow logs before retrying."
  elif git log -1 --pretty=%s | grep -q '^wip('; then
    fail_body="$fail_body The failed issue's work-in-progress is preserved on the branch as the newest wip() commit."
  fi
  exhausted_file=$(git rev-parse --git-path ralph.qa-exhausted 2>/dev/null)
  if [ -s "$exhausted_file" ]; then
    fail_body="$fail_body

QA findings for the failed issue:

\`\`\`
$(head -c 20000 "$exhausted_file")
\`\`\`"
  fi
  remaining=""
  for f in "$RALPH_ISSUES_DIR"/*.md; do
    [ -e "$f" ] && remaining="$remaining
- [ ] $(basename "$f")"
  done
  if [ -n "$remaining" ]; then
    fail_body="$fail_body

Remaining issues:$remaining"
  fi
  fail_body="$fail_body

To retry, push a commit addressing the findings: the workflow re-runs automatically, resumes the failed issue on top of the preserved WIP with a fresh QA budget, and continues the remaining issues. A finished run does not block the branch (and workflow_dispatch with force=true bypasses the gate)."
  comment_issue "$issue_num" "$fail_body"
  die "Ralph stopped before completion (loop exit $loop_rc)."
fi
