#!/bin/bash
# AI-WORKFLOW-MANAGED: generated by setup-ai-workflow.sh; edit source templates or keep a backup before customizing.
# ralph-handoff.sh — hand an approved plan off to the remote workflow.
#
# Local mode produces an approved plan: prd/PRD.md, plus any CONTEXT/ADR doc
# updates from the grill-with-docs skill. This script creates a ralph/<slug>
# branch, commits that plan + docs bundle, and pushes it. The push triggers
# .github/workflows/ralph-remote.yml, which opens a tracking issue, decomposes the
# plan into issues, runs the Ralph dev/QA loop, archives the PRD, and opens a PR.
#
# Usage:
#   ./ralph-handoff.sh [slug]
#
# With no slug, one is derived from the first H1 heading of the PRD file.
set -euo pipefail

# shellcheck disable=SC1091
[ -f .ralph.env ] && . ./.ralph.env
RALPH_PRD_DIR="${RALPH_PRD_DIR:-prd}"
RALPH_PRD_FILE="${RALPH_PRD_FILE:-$RALPH_PRD_DIR/PRD.md}"
RALPH_ISSUES_DIR="${RALPH_ISSUES_DIR:-issues}"

die() { echo "ralph-handoff: $*" >&2; exit 1; }

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//' \
    | cut -c1-50
}

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository."
git remote get-url origin >/dev/null 2>&1 || die "no 'origin' remote configured."
[ -f "$RALPH_PRD_FILE" ] || die "$RALPH_PRD_FILE not found — write the plan first (write-prd skill)."

if ls "$RALPH_ISSUES_DIR"/*.md >/dev/null 2>&1; then
  die "$RALPH_ISSUES_DIR/ is not empty. A hand-off ships the PLAN only; the remote run decomposes it. Remove $RALPH_ISSUES_DIR/*.md, or use local mode (./ralph.sh)."
fi

slug=""
if [ "$#" -ge 1 ]; then slug="$1"; fi
if [ -z "$slug" ]; then
  title=$(grep -m1 -E '^#[[:space:]]+' "$RALPH_PRD_FILE" | sed -E 's/^#[[:space:]]+//') || true
  slug=$(slugify "${title:-plan}")
fi
slug=$(slugify "$slug")
[ -n "$slug" ] || die "could not derive a branch slug; pass one: ./ralph-handoff.sh my-slug"
branch="ralph/$slug"

if git show-ref --verify --quiet "refs/heads/$branch"; then
  die "local branch $branch already exists. Pick another slug or delete it."
fi
if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  die "remote branch $branch already exists. Pick another slug, or close its run first."
fi

echo "Handing off plan on branch: $branch"
git switch -c "$branch"

# Stage only the plan + docs bundle. grill-with-docs adds CONTEXT/ADR files; plain
# grill-me does not — staging whatever exists covers both.
paths=()
for p in "$RALPH_PRD_DIR" "$RALPH_PRD_FILE" CONTEXT.md CONTEXT-MAP.md docs; do
  if [ -e "$p" ]; then paths+=("$p"); fi
done
git add -- "${paths[@]}"

if git diff --cached --quiet; then
  echo "No new plan changes to commit (plan already committed); branching from HEAD."
else
  git -c core.hooksPath=/dev/null commit -m "plan: $slug"
fi

git push -u origin "$branch"

cat <<EONOTE

Plan pushed to origin/$branch. The remote workflow will now:
  1. open a tracking issue (label: ralph:run),
  2. decompose the plan into issues and run the dev/QA loop,
  3. archive the PRD and open a PR for your review.

Watch: the 'ralph-remote' Actions run, and the 'Ralph run: $slug' issue.
EONOTE
